mqtt:
  # mqtt broker in gcloud must be starded
  # on https://console.cloud.google.com/compute/instancesDetail/zones/europe-west1-b/instances/hassio?project=braveo-bubble
  # mosquitto_pub -h 35.190.195.147 -u gcpmosquitto -P 3Ftg43g -p 1883 -t interphone-braveo/switch/ouverture_porte_par_interphone/command -m ON 
  broker: $mqtt_brocker
  port: $mqtt_port
  username: $mqtt_username
  password: $mqtt_password
  # 
  discovery: true
  discovery_prefix: homeassistant
  # will reboot after this delay if mqtt not reachable
  reboot_timeout: 5min
  discovery_unique_id_generator: mac

